Chapter04/LetsChat/Models/ErrorViewModel.cs
using System;

namespace LetsChat.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Chapter04/LetsChat/Controllers/AuthenticationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Facebook;
using Microsoft.Extensions.Logging;

namespace LetsChat.Controllers
{
    [Route("authentication")]
    public class AuthenticationController : Controller
    {
        private readonly ILogger<AuthenticationController> logger;

        public AuthenticationController(ILogger<AuthenticationController> logger)
        {
            this.logger = logger;
        }

        [Route("signin")]
        public IActionResult SignIn()
        {
            logger.LogInformation($"Calling {nameof(this.SignIn)}");
            return Challenge(new AuthenticationProperties { RedirectUri = "/" });
        }

        [Route("signout")]
        [HttpPost]
        public async Task<IActionResult> SignOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }
    }
}

Chapter04/LetsChat/Controllers/FaqController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace LetsChat.Controllers
{
    [AllowAnonymous]
    public class FaqController : Controller
    {
        // GET: Faq
        public ActionResult Index()
        {
            return this.View();
        }        
    }
}

Chapter04/LetsChat/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LetsChat.Models;
using Microsoft.AspNetCore.Authorization;

namespace LetsChat.Controllers
{
    public class HomeController : Controller
    {
        [Authorize]
        public IActionResult Index()
        {
            return this.View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Chapter04/LetsChat/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Chapter04/LetsChat/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Chapter04/LetsChat/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Let's Chat";
    ViewData["UserName"] = "Guest";
    if(User.Identity.IsAuthenticated)
    {
        ViewData["UserName"] = User.Identity.Name;
    }
}
<h1>
  Hello @ViewData["UserName"]! Welcome to chat room - "Let's Chat"
</h1>
<br />

<!-- Template start-->
<div class="main_section">
    <div class="container">
        <div class="chat_container">
            <div class="col-sm-3 chat_sidebar">
                <div class="row">
                    <div class="dropdown" style="text-align:center">
                        <strong>
                            Online Users
                        </strong>
                    </div>
                    <div class="member_list">
                        <ul class="list-unstyled" id="onlineUsers">
                            @*<li class="left clearfix">
                                    <div class="chat-body clearfix">
                                        <div class="header_sec">
                                            <strong class="primary-font">Rishabh Verma</strong>
                                        </div>
                                    </div>
                                </li>*@
                        </ul>
                    </div>
                </div>
            </div>
            <!--chat_sidebar-->
            <div class="col-sm-9 message_section">
                <div class="row">
                    <div class="new_message_head">
                    </div>
                    <!--new_message_head-->

                    <div class="chat_area">
                        <ul class="list-unstyled" id="chatArea">
                            @*<li class="left clearfix">
                                    <span class="chat-img1 pull-left">
                                        <img src="<<Image Url>>" alt="User Avatar" class="img-circle">
                                    </span>
                                    <div class="chat-body1 clearfix">
                                        <p> Image Here</p>
                                        <div class="chat_time pull-right"><<Date Time here>></div>
                                    </div>
                                </li>*@
                        </ul>
                    </div>
                    <div class="message_write">
                        <textarea class="form-control" id="txtMessage" placeholder="Type your message..."></textarea>
                        <div class="clearfix"></div>
                        <div class="chat_bottom"> <a id="sendChat" href="#" class="pull-right btn btn-success">Send</a></div>
                    </div>
                </div>
            </div> <!--message_section-->
        </div>
    </div>
</div>
<!-- Template End-->
<script src="~/lib/jquery/dist/jquery.js"></script>
<link href="~/css/site.css" rel="stylesheet" />
<script src="~/js/signalr-client-1.0.0-alpha1-final.js"></script>
<script src="~/js/signalr-clientES5-1.0.0-alpha1-final.js"></script>
<script src="~/js/signalr-msgpackprotocol-1.0.0-alpha1-final.js"></script>
<script type="text/javascript">
    let hubUrl = '/chatHub';
    let httpConnection = new signalR.HttpConnection(hubUrl);
    let hubConnection = new signalR.HubConnection(httpConnection);

    hubConnection.on('SetUsersOnline', usersOnline => {
        if (usersOnline.length > 0) {
            $('#onlineUsers').innerText = '';
            $.each(usersOnline, function (i, user) {
                addUserOnline(user);
            });
        }
    });

    hubConnection.on('UsersJoined', users => {
        if (users != null && typeof (users) != undefined) {
            appendLine(users.name + ' joined the chat room', 'green');
            addUserOnline(user);
        }
    });

    hubConnection.on('UsersLeft', users => {
        if (users != null && typeof (users) != undefined) {
            appendLine(users.name + ' left the chat room', 'red');
            document.getElementById(users.connectionId).outerHTML = '';
        }
    });

    hubConnection.on('Send', (userName, message, image) => {
        ////<li class="left clearfix">
        ////    <span class="chat-img1 pull-left">
        ////        <img src="https://lh6.googleusercontent.com/-y-MY2satK-E/AAAAAAAAAAI/AAAAAAAAAJU/ER_hFddBheQ/photo.jpg" alt="User Avatar" class="img-circle">
        ////                        </span>
        ////        <div class="chat-body1 clearfix">
        ////            <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia.</p>
        ////            <div class="chat_time pull-right">09:40PM</div>
        ////        </div>
        ////                    </li>

        var listItem = document.createElement('li');
        listItem.className = "left clearfix";

        var spanElement = document.createElement('span');
        spanElement.className = "chat-img1 pull-left";

        var imageElement = document.createElement('img');
        imageElement.alt = userName;
        imageElement.title = userName;
        imageElement.className = "img-circle";
        imageElement.src = image;

        spanElement.appendChild(imageElement);

        var divBody = document.createElement('div');
        divBody.className = "chat-body1 clearfix";
        divBody.title = userName;

        var para = document.createElement('p');
        para.innerText = message;

        var divTime = document.createElement('div');
        divTime.className = "chat_time pull-right";

        var date = new Date();
        var n = date.toDateString();
        var time = date.toLocaleTimeString();

        divTime.innerText = n + " " + time;

        divBody.appendChild(para);
        divBody.appendChild(divTime);

        listItem.appendChild(spanElement);
        listItem.appendChild(divBody);

        document.getElementById('chatArea').appendChild(listItem);
    });

    hubConnection.start();

    $("#sendMessage").click(function () {
        sendMessage();
    });

    function sendMessage() {
        let chatData = $('#txtMessage').val();
        if (chatData != null && chatData.length > 0) {
            hubConnection.invoke('Send', chatData);
            event.preventDefault();
            $('#txtMessage').val("");
        }
    }

    $("#txtMessage").keyup(function (e) {
        if (e.keyCode == 13) {
            sendMessage();
        }
    });

    function appendLine(line, color) {

        var listItem = document.createElement('li');
        listItem.className = "left clearfix";

        var divBody = document.createElement('div');
        divBody.className = "chat-body1 clearfix";

        var para = document.createElement('p');
        para.innerText = line;
        divBody.appendChild(para);
        listItem.appendChild(divBody);
        if (color) {
            listItem.style.color = color;
        }
        document.getElementById('chatArea').appendChild(listItem);
    };

    function addUserOnline(user) {
        if (document.getElementById(user.connectionId)) {
            return;
        }

        var userLi = document.createElement('li');
        userLi.id = user.connectionId;

        userLi.className = "left clearfix";

        var divBody = document.createElement('div');
        divBody.className = "chat-body clearfix";

        var divHeader = document.createElement('div');
        divHeader.className = "header_sec";

        var strong = document.createElement('strong');
        strong.className = "primary-font";

        strong.innerText = `${user.name}`;

        divHeader.appendChild(strong);

        divBody.appendChild(divHeader);

        userLi.appendChild(divBody);

        document.getElementById('onlineUsers').appendChild(userLi);
    }
</script>

Chapter04/LetsChat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Let's Chat</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @*<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>*@
                @*</button>*@
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">.NET Core 2.0 By Example : Let's Chat</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {                        
                        <li>
                            <br/>
                            <form method="post" asp-controller="Authentication" asp-action="SignOut">
                                <button type="submit" class="btn btn-primary">Sign Out</button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li><a asp-area="" class="btn btn-primary" asp-controller="Authentication" asp-action="SignIn">Sign In</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>The app is for demo and learning purposes only. The code is not thoroughly tested and is provided as is without warranties.</p>
            <p>&copy; 2017 - Packt</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>